### ISSUE TITLE
Solving HCaptcha without submit button

### ISSUE THREAD

**Issue by kamikazaliba01** [2captcha/2captcha-python#10]
How can solve HCaptcha without submit button. Is there any way to make something like that `___grecaptcha_cfg.clients[0].L.L.callback("TOKENCAPTCHA")`?

**Comment by blue446** [comment]
I have this same problem

**Comment by 2captcha** [comment]
It's not a good place for such questions.
Please [contact 2captcha support](https://2captcha.com/support/faq/add_ticket) on that, they can assist you.

**Comment by Mohdaalam005** [comment]
hiiii , when i hit url first direct catpcha page is coming i put the response code  but there is no click or submit button how i can verify and navigate to login page i am using java
