### ISSUE TITLE
'TwoCaptcha' object has no attribute 'turnstile'

### ISSUE THREAD

**Issue by JasperXzy** [2captcha/2captcha-python#104]
![Error](https://github.com/user-attachments/assets/209d858d-ed25-4b1f-a4ba-2f03dcecab91)
 When I run the file in examples, it says 'TwoCaptcha' object has no attribute 'turnstile'

**Comment by poplers24** [comment]
Hi! Please tell me what version of Python you are using, and has a similar problem been repeated with examples of other captchas?

**Comment by JasperXzy** [comment]
I'm using python 3.12 and Win11

**Comment by kratzky** [comment]
Please check https://github.com/2captcha/2captcha-python/issues/68#issuecomment-1920974503
