### ISSUE TITLE
Getting ERROR_KEY_DOES_NOT_EXIST when trying to solve normal captcha

### ISSUE THREAD

**Issue by WesleyFreitas472** [2captcha/2captcha-python#108]
I'm trying to solve the captcha bellow. Until yesterday I was able to solve the same type of captcha and now it's only raising an ApiException with `ERROR_KEY_DOES_NOT_EXIST` error message.

```python
self.captcha.normal(f"./image.jpg")
```

![image](https://github.com/user-attachments/assets/a18250fa-da5b-4411-80cc-fd54cf5bcca0)

**Comment by kratzky** [comment]
> isn't better to return 4xx? it's an error on the client side

Yep, it's better, but it's too late to make such kind of changes in the API.
