### ISSUE TITLE
'TwoCaptcha' object has no attribute 'normal'

### ISSUE THREAD

**Issue by TiddlyWiddly** [2captcha/2captcha-python#11]
Getting the error in the title after the following:

```
solver = TwoCaptcha(mykey)
...
try:
    result = solver.normal(base64.decodebytes(captcha))

except Exception as e:
    sys.exit(e)


```

**Comment by 2captcha** [comment]
It's not clear what are you trying to do.
Please share all your code staring from imports.
And also please check [this example](https://github.com/2captcha/2captcha-python/blob/master/examples/normal_base64.py)  if you want to submit image as base64-encoded string or [this example](https://github.com/2captcha/2captcha-python/blob/master/examples/normal_options.py) if you want to submit a file.
