### ISSUE TITLE
Can 2Captcha solve android app's ReCaptcha?

### ISSUE THREAD

**Issue by vanshsantoshi** [2captcha/2captcha-python#115]
It is quite similar to normal ReCaptchas. 
For example, this info is sent to https://www.recaptcha.net/recaptcha/api3/mri (originally in protonbuf)

```
{
  "string_1": "6LeMK_sfAAAAAJLd4foZmo7m3u8pV_J_xxxxx",
  "string_2": "com.example.myApp",
  "string_3": "18.6.1",
  "int_4": 1,
  "string_6": "a28e8f6c-8b3c-4c1b-b15c-4e0ea77189f0",
  "string_7": "30"
}
```

Where "30" is android version (sdk 30 is A11), com.example.myApp is app's unique package name and 18.6.1 is recaptcha android library version. Device infos are further sent on /mlg requests

**Comment by kratzky** [comment]
For requests not related to the library, please use contact form on the website: https://2captcha.com/support/tickets/new
