### ISSUE TITLE
Implement with selenium

### ISSUE THREAD

**Issue by Blakeboy02** [2captcha/2captcha-python#2]
Hi is there a way to implement 2 captcha with selenium thanks.

**Comment by 2captcha** [comment]
> Hi is there a way to implement 2 captcha with selenium thanks.

Hi!
You can use selenium or any other browser automation framework for your task and at the same time use our package to interact with 2captcha API.
Use 2captcha to get an answer for your captcha, then use selenium to submit the answer.
