### ISSUE TITLE
Move `__version__` out of the twocaptcha package

### ISSUE THREAD

**Issue by sahil-b-shah** [2captcha/2captcha-python#24]
Move the `__version__` variable definition outside of the twocaptcha package. When `setup.py` tries to import that value, it causes an import of the `requests` library (via the `ApiClient` import) in `twocaptcha/__init__.py` . This breaks builds because it necessitates that users install `requests` before `twocaptcha` rather than being able to install libraries all in one go (e.g. via `pip install -r requirements.tx`).

**Suggestion:** Move it to a `__version__.txt` file and have `setup.py` and `twocaptcha/__init__.py` read it in as a value.

**Comment by costastf** [comment]
This should solve #16 .

**Comment by 2captcha** [comment]
Can you guys make a pull request that properly implements the recommended approach?
Will be really appreciated.

**Comment by 2captcha** [comment]
fixed with #28 in v1.1.1 thanks to @nathanielobrown
