### ISSUE TITLE
Selenium?

### ISSUE THREAD

**Issue by KeparYTbcc** [2captcha/2captcha-python#27]
So i wonder how it should works with selenium, beacouse i tried lot of ways and it still not completing the h-captcha,
take a look at it:

**Comment by KeparYTbcc** [comment]
```
def solve():
    import sys
    from twocaptcha import TwoCaptcha
    result = None

    sitekey = "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"
    api_key = key2captcha
    solver = TwoCaptcha(api_key)
    try:
        result = solver.hcaptcha(
            sitekey=sitekey,
            url=driver.current_url
        )

    except Exception as e:
        sys.exit(e)

    return result
    
textarea = driver.find_element(By.NAME, 'h-captcha-response')
solution = solve()
code = solution['code']
driver.execute_script(f"var ele=arguments[0]; ele.innerHTML = '{code}';", textarea)
```

**Comment by KeparYTbcc** [comment]
but it wont complete the h-Captcha at all

**Comment by KeparYTbcc** [comment]
giving me no error

**Comment by KeparYTbcc** [comment]
@kratzky support?

**Comment by kratzky** [comment]
We don't discuss here any topics not related to the python module itself.
The module's task is to interact with 2Captcha API and return you the answer/token. The rest is you own task.

My first recommendation for such kind of cases: 
- make it working in a browser without any automation
- when done, automate it with your favourite webdriver

I'm pretty sure you need to execute a callback on your target website.
