### ISSUE TITLE
GeeTest ERROR_CAPTCHA_UNSOLVABLE

### ISSUE THREAD

**Issue by lly835** [2captcha/2captcha-python#32]
https://2captcha.com/demo/geetest

**Comment by westz36** [comment]
same issue

**Comment by sumukhah** [comment]
Same issue for me too

**Comment by jianjye** [comment]
Same issue for me +1. Does 2captcha still work for geetest?

**Comment by 2captcha** [comment]
Just make sure you get a new `challenge` value before solving each captcha.
On https://2captcha.com/demo/geetest you should get the challenge value from `https://2captcha.com/api/v1/captcha-demo/gee-test/init-params?t=${ts}` where `ts` is the timestamp.

**Comment by Juanchobanano** [comment]
Thanks for the anwser, however I am a little confused now. Where should I get the "challenge" value from this  [website](https://www.geetest.com/en/demo) for example?

**Comment by 2captcha** [comment]
> Thanks for the anwser, however I am a little confused now. Where should I get the "challenge" value from this [website](https://www.geetest.com/en/demo) for example?

From URL: `https://www.geetest.com/demo/gt/register-enFullpage-official?t=${ts}` where ts is the timestamp.

**Comment by Juanchobanano** [comment]
Thanks again! How did you find this URL? I want to scrape several places, but I think I don't understand the general way to determine which URL will do the job independently of the website.

**Comment by 2captcha** [comment]
> Thanks again! How did you find this URL? I want to scrape several places, but I think I'm not understanding the general way to determine which URL will do the job independently of the website.

Start from inspecting the html source, looking for `challenge`, then inspect the network requests, if no luck - dive into javascript code of the website.
There's no universal solution for any website.

**Comment by Juanchobanano** [comment]
Hi! Thanks for the answer. I have been struggling for hours to find the URL of the Geetest Recaptcha in this [website](https://www.leolist.cc/personals/female-escorts/greater-toronto/city_toronto_160hr_sexy_latina_woman_islington_av_albion_rd-6489763?source=list). Basically when you press on the buttons in the contact information, it displays a geetest recaptcha. Is it possible you can help me with this? I want to extract information from this website on a daily basis, so I think I will use the service very frequently.

**Comment by flo-wolf** [comment]
For anyone wondering, you can inspect your page with the chrome devtools and view all network calls. 
In the attached screenshot you can see the url used to get a challenge for the geetest demo on the 2captcha website:

![image](https://user-images.githubusercontent.com/1511848/233518670-b55db548-1d60-4192-a2df-172e6668676b.png)


Here is the response:

![image](https://user-images.githubusercontent.com/1511848/233518764-d03dc409-c7c7-488e-9c65-64e271840a3b.png)

You just got to do that for your own page, and find out the url used to GET a challenge.
