### ISSUE TITLE
'TwoCaptcha' object has no attribute 'normal'

### ISSUE THREAD

**Issue by MaxMady** [2captcha/2captcha-python#33]
Anyone help me?
```py
from twocaptcha import TwoCaptcha

```

**Comment by 2captcha** [comment]
Probably you have another module with the same name installed.

Do the following:
```python
import twocaptcha
print(twocaptcha.__version__)
print(dir(twocaptcha.TwoCaptcha))
```

and then show me the output please.

**Comment by Chan0920** [comment]
Hi, i am facing the same issue as well. Apparently, though "2captcha-python" is installed, each time it tries to run it will try to install the package name "TwoCaptch". This is why the issue is being shown. I faced this issue before on other packages like "websocket  and websocket-client" and its very frustrating as there is a conflicting naming of package.

**Comment by jeff41101** [comment]
I'm having the same issue, mind ask how this is solved?
So I uninstalled TwoCaptcha and installed captcha-python but this is what I get
from twocaptcha import TwoCaptcha
ImportError: cannot import name 'TwoCaptcha' from 'twocaptcha' (unknown location)

**Comment by githubpaycon** [comment]
Hello this worked for me, following the steps of this in Pypi
https://pypi.org/project/2captcha-python/#installation

pip3 install 2captcha-python

```
from twocaptcha import TwoCaptcha
solver = TwoCaptcha(key_captcha)        
result = solver.normal(file=...)
```

**Comment by justabettergamer** [comment]
I tried to resolve click captchas on 2captcha website and via python, but both got timeout or error captcha unsolvable.. any fix?
i'm using jpg screenshot of the captcha

**Comment by nitroz3us** [comment]
Hi, I'm currently having the same issue, even after what @githubpaycon has mentioned. Any updates? I've took a look at the TwoCaptcha wrapper.py, there isn't any "normal" function
