### ISSUE TITLE
I can't solve Geetest Captcha

### ISSUE THREAD

**Issue by Juanchobanano** [2captcha/2captcha-python#34]
I am testing the captcha geetest solve from https://2captcha.com/demo/geetest
I have replaced gt = 81388ea1fc187e0c335c0a8907ff2625 and challenge but it doesn't work.
Error occurred: ERROR_CAPTCHA_UNSOLVABLE

**Comment by 2captcha** [comment]
Please see [comment](https://github.com/2captcha/2captcha-python/issues/32#issuecomment-1088438476) for #32
