### ISSUE TITLE
What should I put in data parameter inside the response with already solved hCaptcha?

### ISSUE THREAD

**Issue by korovokliu** [2captcha/2captcha-python#35]
When I'm requesting page with requests library I receive this respoce from a server:

`{'captcha_key': ['You need to update your app to join this server.'], 
'captcha_sitekey': 'a9b5fb07-92ff-493f-86fe-352a2803b3df', 
'captcha_service': 'hcaptcha', 
'captcha_rqdata': 'OccZocPS0udA/9MOyn4qvfLuti5qTqBYoyNljA7F5cT8JBJrhBWRhw0TEDEFDTOOHMnE6jvE2WzhbGjvDN4hk9fxZkcvQ7Bgjjd/QEJEXReGJWyyxhB0HFSjFjRjn6H23PJjdTyRWpDrTjhV6l/qDb4O14C9XiiXfKF2hQgh', 
'captcha_rqtoken': 'IlZFamJXMkdPZ1BiMTJsYlJhQ2NMYlFOaHJTWWdtUjl0NjBhQ0cyZTFCWmhtd01xc0pYeCtMMHhENXNKcmpWRHJPN0FrM2c9PWk5Zk5NUmRRdTNjdFRTTDQi.Yn7Hbw.CNj-_pg2pNmt47a-9OG8PyevmHA'}`

then I'm using twocaptcha for solving this captcha in that manner:
`recaptcha_answer = solver.hcaptcha(sitekey="a9b5fb07-92ff-493f-86fe-352a2803b3df",
                                       url=f'https://discord.com/api/v9/invites/{my_invite}',
                                       defaultTimeout=600)`

and this function return captchaId and code.

The question is where and what should I put in data parameter if captcha is invisible? Cause If I requesting this page again with just a code as captcha_key server response for solving captcha again. I think I just give the wrong payload.

**Comment by 5t0n1e** [comment]
I'm not 100% sure but For the url you'll just have to use https://discord.com/channels/@me
And you'll have to pass the rq_data in the data parameter. I suppose you're also writing in discord.py-self. I'm also working with this module so if I have it figured out I'll get back to you.
