### ISSUE TITLE
Using a base64 string instad of image file

### ISSUE THREAD

**Issue by victorlane** [2captcha/2captcha-python#36]
Hi, I have a problem understanding something of the API. 

I've laid out my question on Stackoverflow.

https://stackoverflow.com/questions/72555278/using-a-base64-string-instead-of-image-file-with-2catpcha-api

**Comment by kratzky** [comment]
Take a look on the example:
https://github.com/2captcha/2captcha-python/blob/master/examples/normal_base64.py

**Comment by victorlane** [comment]
> Take a look on the example: https://github.com/2captcha/2captcha-python/blob/master/examples/normal_base64.py

This doesn't really answer my question as I'm not trying to read from a file. I already have a base64 image in a string, I'm really just trying to convert it to the right type for twocaptcha
