### ISSUE TITLE
Errors in module

### ISSUE THREAD

**Issue by kratzky** [2captcha/2captcha-python#5]
1. `apiKey` is ignored if passed inside the options
2. if the `callback` is passed, captchaId should be returned, but it is polling the api to get an answer
~~3. AttributeError: 'TwoCaptcha' object has no attribute 'getResult' when calling getResult method~~

**Comment by 524c** [comment]
Hello,

I have a Key API, but I did not understand where I get a sitekey. Can someone help me please?

Thanks.
