### ISSUE TITLE
It's new version (v_1.2.0) not working for linux, may be for windows also but older one works fine.

### ISSUE THREAD

**Issue by subash1237** [2captcha/2captcha-python#53]
twocaptcha couldnot be resolved.
result=solver.normal('/path') 

Error:
    'normal' not found

**Comment by kratzky** [comment]
Could you please provide all the code you use starting from the imports so we can try to reproduce the issue?

**Comment by hobrin** [comment]
from twocaptcha import TwoCaptcha
solver = TwoCaptcha(anticaptcha_key)
solver.normal('/path')

**Comment by kratzky** [comment]
> ```python
> from twocaptcha import TwoCaptcha
> solver = TwoCaptcha(anticaptcha_key)
> solver.normal('/path')
> ```

Just tested on a clean linux installation:

```python
from twocaptcha import TwoCaptcha
solver = TwoCaptcha('KEY')
res = solver.normal('./cap.jpg')
print(res)
```
Works fine and prints the result.



Could you please run the following code and show the result?

```python
import twocaptcha
print(twocaptcha.__version__)
print(dir(twocaptcha.TwoCaptcha))
```
