### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by baongoc159** [2captcha/2captcha-python#55]
Hi team,
what causing this error:
HTTPSConnectionPool(host='2captcha.com', port=443): Max retries exceeded with url: /in.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
I could run the code in different computer and get result. But change to this new computer, using window subsystem on linux. I meet this
Thanks

**Comment by kratzky** [comment]
But what's your current date on the WSL?

**Comment by kratzky** [comment]
And also try to install `pip_system_certs`

**Comment by baongoc159** [comment]
The date seems correct
(.venv) n:~/votWeb$ date
Fri Jun  9 16:44:45 +07 2023
(.venv) n:~/votWeb$ sudo ntpdate pool.ntp.org
 9 Jun 16:45:17 ntpdate[19467]: adjust time server 103.130.217.41 offset -0.037110 sec
 
pip_system_certs is install but the error still the same.

**Comment by kratzky** [comment]
Sorry, but I have no more suggestions for your case. Can only recommend to search for `wsl python CERTIFICATE_VERIFY_FAILED` and try the suggestions.
