### ISSUE TITLE
import error follow on document example

### ISSUE THREAD

**Issue by ChiHangChen** [2captcha/2captcha-python#58]
I follow the document using this line
```
from twocaptcha import TwoCaptcha
```
But it will throw an error `ImportError: cannot import name 'TwoCaptcha' from 'twocaptcha' (unknown location`

Shouldn't it be
```
from twocaptcha.solver import TwoCaptcha
```
in document?

I am using 1.2.1 version

**Comment by kratzky** [comment]
No, I don't think so. It works the way it's described in the doc.

<img width="689" alt="image" src="https://github.com/2captcha/2captcha-python/assets/17198195/74a93760-6546-40b2-be6a-b335e381a0ed">

Probably you have another module installed that has `twocaptcha` namespace.

**Comment by ChiHangChen** [comment]
You probably right, I have another lib `TwoCaptcha==0.0.1`
After remove it and can import as document decription,
But I think
```
from twocaptcha import TwoCaptcha
```
and
```
from twocaptcha.solver import TwoCaptcha
```
Both work for `2captcha-python==1.2.1`

**Comment by hacknapier** [comment]
@ChiHangChen use this documentation https://github.com/flyCaptcha/flyCaptcha
