### ISSUE TITLE
Use Proxy

### ISSUE THREAD

**Issue by LeilaSchooley** [2captcha/2captcha-python#7]
How can I use a proxy with the solver? I'd be interested in doing so in order to change IP.

**Comment by 2captcha** [comment]
Hi!

Yes, you can pass a proxy with your captcha in the following format and our API will use the proxy to solve your captcha:
```
        proxy={
            'type': 'HTTPS',
            'uri': 'login:password@IP_address:PORT'
        }
```

https://github.com/2captcha/2captcha-python/blob/master/examples/recaptcha_v2_options.py#L18
