### ISSUE TITLE
ReCAPTCHAv2 not passing on reportcontent.google.com

### ISSUE THREAD

**Issue by lemeow125** [2captcha/2captcha-python#71]
### Describe the issue

The ReCAPTCHAv2 code returned by the 2captcha-python library is not working for this [URL](https://reportcontent.google.com/forms/dmca_search?hl=en&utm_source=wmx&utm_medium=deprecation-pane&utm_content=legal-removal-request)

There are no errors present when sending a request, or receiving the code. The CAPTCHAv2 code is correctly entered but clicking the checkbox still shows the challenge rather than passing it
![1](https://github.com/2captcha/2captcha-python/assets/63192778/0e93cff5-52dd-4531-8bec-70c93983fb8a)
![2](https://github.com/2captcha/2captcha-python/assets/63192778/1ca82f33-ffe8-4f25-b5f8-f3b912b96e81)

Per 2CAPTCHA support's suggestion on our ticket, we have also tested sandbox mode to isolate any issues. This does not work. We have also tried the provided Firefox addon/extension and that also does not work. The same issue persists

**Comment by lemeow125** [comment]
This issue popped up only recently. Before this ReCAPTCHAv2 request codes were valid clicking the checkbox automatically passes the test.
![image](https://github.com/2captcha/2captcha-python/assets/63192778/0788acf1-87c3-4dbb-b3e5-45c406db371e)

**Comment by lemeow125** [comment]
As per our testing, we've found that manually solving the CAPTCHAv2 challenge and passing the resulting code to a different session/tab works. With this we are able to get the expected behavior and ReCAPTCHAv2 challenge is passed.

https://github.com/2captcha/2captcha-python/assets/63192778/66d3e65b-50ae-4c89-a135-fb5264c0b771

The ReCAPTCHAv2 code does seem to change once the checkbox is clicked on the 2nd browser tab/session.

**Comment by OwenChen0911** [comment]
I've met same issue, please help me

**Comment by AliCl0ner** [comment]
same issue

**Comment by OwenChen0911** [comment]
> same issue

how do you deal with token?  

 driver.execute_script(f"document.getElementById('g-recaptcha-response').value='{response}';")???

**Comment by OwenChen0911** [comment]
> ### Describe the issue
> The ReCAPTCHAv2 code returned by the 2captcha-python library is not working for this [URL](https://reportcontent.google.com/forms/dmca_search?hl=en&utm_source=wmx&utm_medium=deprecation-pane&utm_content=legal-removal-request)
> 
> There are no errors present when sending a request, or receiving the code. The CAPTCHAv2 code is correctly entered but clicking the checkbox still shows the challenge rather than passing it ![1](https://private-user-images.githubusercontent.com/63192778/311966074-0e93cff5-52dd-4531-8bec-70c93983fb8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzE5MDYsIm5iZiI6MTcyNjEzMTYwNiwicGF0aCI6Ii82MzE5Mjc3OC8zMTE5NjYwNzQtMGU5M2NmZjUtNTJkZC00NTMxLThiZWMtNzBjOTM5ODNmYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTNkNzljNjY1ZWE5MjJlY2E4NGI4NDQ4NTY5ZDRlYTVhNDc3MTJhNGU5MDhmZjczNjY0MjhkYzRlZDAzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1O7YlK9aVbPYSXf1R0O3OiTo3ENFZ6a6YUIkxGSZdiw) ![2](https://private-user-images.githubusercontent.com/63192778/311966144-1ca82f33-ffe8-4f25-b5f8-f3b912b96e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzE5MDYsIm5iZiI6MTcyNjEzMTYwNiwicGF0aCI6Ii82MzE5Mjc3OC8zMTE5NjYxNDQtMWNhODJmMzMtZmZlOC00ZjI1LWI1ZjgtZjNiOTEyYjk2ZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MjJjYWJkOGM5MjM4NDhmNzEzMWIxNjgzMGE2MTNjOGMyNDM5NTU2NGUzNjdiYzU3MTVkNzkwMzQ5ZDExMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-VNJW55dhtfV9dYtlNkqA2h-7UfjTj7_Iq_d3W66TpA)
> 
> Per 2CAPTCHA support's suggestion on our ticket, we have also tested sandbox mode to isolate any issues. This does not work. We have also tried the provided Firefox addon/extension and that also does not work. The same issue persists

hello?     can you help me?

**Comment by kratzky** [comment]
For any questions not related directly to the Python module code please [contact 2Captcha support team ](https://2captcha.com/support/tickets/new) directly.
