### ISSUE TITLE
FunCaptcha ERROR_CAPTCHA_UNSOLVABLE 

### ISSUE THREAD

**Issue by Tongcheng** [2captcha/2captcha-python#78]
Hi there, I have tried four times to solve FunCaptcha, but it always returns ERROR_CAPTCHA_UNSOLVABLE  after waiting for 40-80sec. Any thoughts why? I tried both the python wrapper and URL query (to the .php).

**Comment by AgenChicken24** [comment]
I am having the same issue.
I am trying to solve the captcha for the Outlook account creation and the first time I tried it, I solved it, but I hadn't implemented the submission. After that, I get that error with no clue as to what to do.

Did you manage to find a solution for this?

**Comment by dzmitry-duboyski** [comment]
@Tongcheng @AgenChicken24 You can write a ticket on the page https://2captcha.com/support/tickets/new and ask your question . When creating a ticket, do not forget to specify the page where you are trying to solve the captcha.

**Comment by lavarthan** [comment]
is there any solution for this? facing the same issue
