### ISSUE TITLE
Discord's api captcha bypass question

### ISSUE THREAD

**Issue by slayy2357** [2captcha/2captcha-python#83]
### Idea :

Use discord api to try joining the discord server, get captcha sitekey & rqdata of the captcha that block you and solve it to finaly join the server.

### Code :

`r = requests.post("https://discord.com/api/v9/invites/" + code, headers=headers).text`
`...`
`result = solver.hcaptcha(
                        sitekey=str(sitekey),
                        url='https://discord.com/channels/@me',
                        data=str(rqdata),
                    )
                print(str(result))`

### Result (output) : 

`{'captchaId': '76536955165', 'code': 'P1_...'}`

### Question :

How to use the returned value (result) to bypass the discord captcha ? Thanks

**Comment by arthurauffray** [comment]
If im not misunderstanding your question, the returned value would be used in the "captchaResponse" field of a request to the discord API, or to fill the hidden input of a form.

![image](https://github.com/2captcha/2captcha-python/assets/51604173/9dc01dde-6962-49f1-af38-a4b0d2ce017a)
`g-recaptcha-response` hidden input

**Comment by dzmitry-duboyski** [comment]
@slayy2357 To solve recaptcha, you can also use alternative methods such as [grid method](https://2captcha.com/2captcha-api#grid) or [coordinates](https://2captcha.com/2captcha-api#coordinates).

You can also write a ticket on the page https://2captcha.com/support/tickets/new and ask your question there.
