### ISSUE TITLE
How to submit if the form haven't submit button?

### ISSUE THREAD

**Issue by crackwei** [2captcha/2captcha-python#9]
Hello, i try to use 2captcha-python to resolve the cloudflare's hcaptcha, but the scripts haven't submit button, once i force submit, it will prompt "wrong captcha", how to solve this problem?

![nosubmit](https://user-images.githubusercontent.com/10041637/104966276-6e88ad80-5a1b-11eb-8277-97b7b9a3b699.png)

**Comment by 2captcha** [comment]
I don't think you ask this in a right place.
As I see on your screenshot, there's [`<form>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) HTML tag. So you can try to submit the form using [`submit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) method.
